version: '3.9'

services:
  db_express:
    container_name: db_express
    hostname: ${MY_ORACLE_HOSTNAME}
    image: container-registry.oracle.com/database/express:latest
    ports:
      - 1521:1521
    environment:
      - ORACLE_PWD=${MY_ORACLE_PASSWORD}
    volumes:
      - db_volume:/opt/oracle/oradata
      
  ords:
    container_name: ords
    image: container-registry.oracle.com/database/ords:latest
    ports:
      - 8181:8181
    volumes: 
      - ./db/variables:/opt/oracle/variables
    restart: always
    depends_on:
      - db_express

  chrome:
    image: selenium/standalone-chrome:latest
    hostname: chrome 
    privileged: true
    shm_size: 2g
    ports:
      - 4444:4444

  bot:
    container_name: bot
    build: ./bot
    environment:
      - DISCORD_API_KEY=${DISCORD_API_KEY}
    depends_on:
      - db_express
      - ords
      - chrome
      
volumes:
  db_volume:
    external: false