version: '3.9'

services:
  devdb:
    container_name: devdb
    image: container-registry.oracle.com/database/express:latest
    ports:
      - 1521:1521
    environment:
      - ORACLE_PWD=1230123
    volumes:
      - dev-vol:/opt/oracle/oradata
    hostname: oracledev
  ords:
    container_name: ords
    image: container-registry.oracle.com/database/ords:latest
    ports:
      - 8181:8181
    restart: always
    depends_on:
      - devdb
    volumes:
      - ./variables:/opt/oracle/variables
  volumes:
    dev-vol:
      name: db-vol
      external: false
      networks:
    default:
      name: demo-network
