version: '3.9'

services:

  chrome:
    image: selenium/standalone-chrome:latest
    hostname: chrome 
    privileged: true
    shm_size: 2g
    ports:
      - 4444:4444

  test-bot:
    build: .
    environment:
      - DISCORD_API_KEY=${DISCORD_API_KEY}
      - TESTING_GUILD_ID=${TESTING_GUILD_ID}
    depends_on:
      - chrome