#!/bin/bash
# Tests and builds *only* bot functionality.
echo Rebuilding bot...
echo Docker downing...
docker-compose down 

echo Docker Building the bot image...
docker-compose build --no-cache test-bot

echo Docker upping...
docker compose up